title: Joel Kores Blog
description: I am a full-stack software engineer, I bring a unique combination of passion, hard work, and skill to every project I tackle. With a strong foundation in both front-end and back-end technologies, I am able to design and develop complete, functional web applications from start to finish. My drive for excellence fuels my ability to quickly learn new technologies and tools, and my attention to detail ensures that each project is delivered to the highest standards. Whether working on a team or independently, I am always striving to find creative solutions to complex problems and to deliver exceptional results. My passion for technology and programming, combined with my commitment to delivering quality work, make me an asset to any organization.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.k0r3s.me" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: https://twitter.com/K0r3s #if your site has a twitter account, enter it here

# Author Settings
author: Joel Kores # add your name
author-img: avatar.jpg # add your photo
about-author: I am a Full Stack Software Engineer. Always hungry to keep learning. # add description
social-twitter: K0r3s # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: 0xAckerMan # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: joelkores1@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
